steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/felipe-backend
      - -f
      - backend/Dockerfile
      - .
    dir: felipe

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/felipe-backend

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - felipe-backend
      - --image=gcr.io/$PROJECT_ID/felipe-backend
      - --region=us-central1
      - --platform=managed
      - --no-allow-unauthenticated
      - --set-env-vars=GH_REPO=dankobuy-ops/Felipe
